### ISSUE TITLE
ARC compilation issues

### ISSUE THREAD

**Issue by cobarx** [lmirosevic/GBPing#10]
I'm unable to get GBPing to compile on the latest iOS SDK. In the section:
```
//clean up dispatch queue
if (self.setupQueue) {
    //foo check that this actually works
    dispatch_release(self.setupQueue);
    self.setupQueue = nil;
}
```
it complains that 'release' is not available in automatic reference counting mode for the dispatch_release call.

Prior to iOS 9, I was able to comment out the dispatch_release line and make setupQueue into a strong reference. However doing that with the new SDK causes a EXC_BAD_ACCESS exception at:
`    NSArray *addresses = (__bridge NSArray *)CFHostGetAddressing(_hostRef, &resolved);`
because _hostRef is null.

I should note that we are pinging 3 different hosts, so that may be setting up some unusual conditions.

**Comment by lmirosevic** [comment]
I'm a little short on time to check this myself but I would more than happily accept a PR for this!

Sent from my mobile device.

--

Luka Mirosevic | Founder | luka@goonbee.com | +43 664 5412921

Goonbee e.U.
Sollingergasse 28/13, A-1190 Wien
FN 437116v

This email and its attachments may be confidential, privileged and protected from disclosure. If you received this communication by mistake, please don't forward it to anyone else, please erase all copies and attachments, and please let me know that it went to the wrong person. Thanks.

**Comment by lmirosevic** [comment]
Fixed in `1.3.0`

**Comment by cobarx** [comment]
Thanks so much. I had put together a fix but wasn't sure if you were willing to drop iOS 5 support and was trying to figure out how to get that to work.

**Comment by lmirosevic** [comment]
Yeah iOS 5 is old enough now to drop it IMP
