### ISSUE TITLE
_hostRef deallocation on separate thread causing EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mosobase** [lmirosevic/GBPing#18]
Kind of hard to explain this one, mainly because its hard to test. The _hostRef variable used in `-(void)setupWithBlock:` is released in `-(void)stop`, this means theres a slim chance that even after checking that the value is !nil there is a small window where it could become nil causing this error, I ran into that today

**Comment by lmirosevic** [comment]
Thanks for the PR! It's been merged and will be in the next release.
