### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by mknippen** [lmirosevic/GBPing#23]
My apologies if I'm missing this and it will already work, but this library could really use IPv6 support!

**Comment by tofubeer** [comment]
Our app was rejected due to lack of IPv6 support as per: https://developer.apple.com/news/?id=05042016a

**Comment by prernarana** [comment]
IPv6 support missing :(

**Comment by lmirosevic** [comment]
IPv6 support now added thanks to @petr-vysotskiy in #32
