### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by vinthewrench** [lmirosevic/GBPing#30]
please make the library build on OS X also.

**Comment by syamalach** [comment]
Oh! it means right now it is not supporting OSX applications??

**Comment by vinthewrench** [comment]
I have have branched it and will try to build an OS X project

**Comment by syamalach** [comment]
Thanks a lot, please notify us once it was done....

**Comment by kaishin** [comment]
I have just tried and this works fine on OSX. Not sure what issue the other commenters are having.

**Comment by lmirosevic** [comment]
Thanks for the info! Closing for now.
