### ISSUE TITLE
Xcode 9 Beta 3 issues

### ISSUE THREAD

**Issue by mikeKane** [lmirosevic/GBPing#39]
GBPing is unable to compile with the latest Xcode 9 Beta 3.

There is alot of complaining about expected parameter declarations for ICMPHeader.h but I think thats just the tip of the ice berg as Apple LLVM 9.0 has too many errors emitted.

 Has anyone else run into these issues?

**Comment by lmirosevic** [comment]
Could you please try with `1.4.1` and confirm if that fixes it?

**Comment by mikeKane** [comment]
Yes, it fixes it! Thanks
