### ISSUE TITLE
RTT is not LATENCY

### ISSUE THREAD

**Issue by AndroidAuth** [lmirosevic/GBPing#49]
LATENCY:    The amount of time physically required for media to travel depending on media length and distance that need to be covered

RTT:   Round Trip Trime,  A round trip time required to travel from source to destination and vice versa.

So there is no way of getting latency from this library in ms ?

**Comment by lmirosevic** [comment]
You can approximate it by dividing by two.

To measure true latency you would need to have a controlled server (some routers at the destination could also work). This is a library that implement the well-known ping protocol which runs over ICMP. ICMP is given low priority so you would want to use a purposeful TCP/UDP based implementation to measure true latency.

**Comment by AndroidAuth** [comment]
got it , thank you for your help
