### ISSUE TITLE
TTL not set correctly

### ISSUE THREAD

**Issue by FroeMic** [lmirosevic/GBPing#51]
I noticed that the TTL of the returned PingSummary objects is not set correctly. In the current implementation it is set to the TTL with which the package was sent with, but it should be the TTL of the response.

*Quick Fix:* add the following code after line  410
```
const struct IPHeader   *ipPtr;
if ([packet length] >= sizeof(IPHeader)) {
    ipPtr = (const IPHeader *)[packet bytes];
                            
     pingSummary.ttl = ipPtr->timeToLive;
}
```

https://github.com/lmirosevic/GBPing/blob/2da62ed396affd9f33748e2c94d4b4cb97374b91/GBPing/GBPing.m#L410

**Comment by lmirosevic** [comment]
Published as `1.5.1`. Thanks for the PR 👍
