### ISSUE TITLE
Ping timeout delegate never called

### ISSUE THREAD

**Issue by DigitalRogues** [lmirosevic/GBPing#6]
So unless I'm not understanding how it works, the didTimeoutWithSummary delegate method never seems to get called even though the timeout is set to the default 2 seconds.

I'm testing with the link conditioner set to 100% loss so GBPing just sends out a bunch of pings but obviously never receives a response, so I would expect after a few pings the timeout delegate should have been called.

any pointers?

**Comment by mikumi** [comment]
I have experienced this as well with the new version. Try using 1.1.0 as a workaround:

pod 'GBPing', :git => 'https://github.com/lmirosevic/GBPing', :commit => '621f37a'

**Comment by vladasdrejeris** [comment]
I have fixed the issue with timeout not being called. Just update the "sendLoop" method in GBPing.m class to this:

-(void)sendLoop {
    @autoreleasepool {
        while (self.isPinging) {
            [self sendPing];
            
            NSTimeInterval runTil = CFAbsoluteTimeGetCurrent() + self.pingPeriod;
            NSTimeInterval time = 0;
            while (runTil > time) {
                [[NSRunLoop currentRunLoop] runUntilDate:[NSDate distantFuture]];
                time = CFAbsoluteTimeGetCurrent();
            }
        }
    }
}

**Comment by lmirosevic** [comment]
Fixed in `1.2.1`
