### ISSUE TITLE
Enable OS X Support

### ISSUE THREAD

**Issue by cobarx** [lmirosevic/GBPing#9]
It would be great if you could modify the podspec to include OS X compatibility. We are using GBPing on both iOS and OS X without issues, so I know it works properly. 

Right now I have to add the GBPing sources to my own pod rather than being able to track the official pod. It would be great to not have to do the maintenance to keep in sync with the main tree.

**Comment by lmirosevic** [comment]
`1.2.0` now adds OS X compat
